# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "thalassophobia:glow_fish",
    "alexsmobs:snow_leopard",
    "thalassophobia:bathotrap_natural_spawn",
    "horrrs_pvz:chompiranha",
    "illager_world_war:villager_soldier_medic",
    "alexsmobs:seal",
    "thalassophobia:riffhead",
    "horrrs_pvz:mechanical_nut_wall",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "thalassophobia:blobfish",
    "thalassophobia:colossoteus_jumping_spawn",
    "thalassophobia:sea_snake",
    "valarian_conquest:drawbridge",
    "ancient_elements:infested_crystal",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "illager_world_war:cannon_with_soldier_villager",
    "thalassophobia:liopleurodon_fossil_entity",
    "minecraft:llama",
    "alexsmobs:maned_wolf",
    "thalassophobia:liopleurodon",
    "graveyard:skeleton_creeper",
    "rlovelyr:bunny2",
    "alexsmobs:skreecher",
    "horrrs_pvz:citron",
    "minecraft:tadpole",
    "valarian_conquest:troll",
    "minecraft:dolphin",
    "ancient_elements:craterborn_scream",
    "thalassophobia:jellyfish",
    "alexsmobs:gelada_monkey",
    "thalassophobia:sea_sludge_spawn",
    "horrrs_pvz:marigold",
    "ancient_elements:bell_effect",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "thalassophobia:cookie_cutter_shark",
    "graveyard:nightmare",
    "alexsmobs:grizzly_bear",
    "valarian_conquest:gate_entity",
    "alexsmobs:murmur_head",
    "horrrs_pvz:snapdragon",
    "thalassophobia:maka_maka_natural_spawn",
    "illager_world_war:pillager_soldier_with_flamethrower",
    "minecraft:bee",
    "graveyard:reaper",
    "alexsmobs:devils_hole_pupfish",
    "ancient_elements:titanium_armor_effect",
    "thalassophobia:big_catfish",
    "minecraft:illusioner",
    "tombstone:spectral_wolf",
    "thalassophobia:crab",
    "block_factorys_bosses:big_cage_skelly",
    "zombiesmore:explosive_zombie",
    "thalassophobia:sea_sludge_natural_spawn",
    "thalassophobia:sea_sludge",
    "thalassophobia:yeti_crab_natural_spawn",
    "minecraft:mooshroom",
    "alexsmobs:bison",
    "ancient_elements:inferno_fusion_bomb_primed",
    "minecraft:drowned",
    "ancient_elements:singularity",
    "minecraft:axolotl",
    "horrrs_pvz:imitater",
    "valarian_conquest:male_citizen",
    "alexsmobs:gorilla",
    "ancient_elements:stone_golem",
    "illager_world_war:outpost_check",
    "alexsmobs:tusklin",
    "horrrs_pvz:nut_wall",
    "quark:crab",
    "thalassophobia:megalodon",
    "illager_world_war:villager_soldier_playing_trumpet",
    "alexsmobs:cosmic_cod",
    "alexsmobs:underminer",
    "illager_world_war:plane",
    "rlovelyr:vanilla",
    "illager_world_war:pillager_plane_overworld_spawn",
    "minecraft:wandering_trader",
    "zombiesmore:boomer_zombie",
    "alexsmobs:kangaroo",
    "block_factorys_bosses:cage_skelly",
    "zombiesmore:cursed_head",
    "thalassophobia:frilled_shark",
    "ancient_elements:ghostly_miner",
    "ancient_elements:drimble",
    "alexsmobs:hummingbird",
    "thalassophobia:basking_shark",
    "valarian_conquest:wooden_gate",
    "mutantmonsters:mutant_zombie",
    "thalassophobia:yeti_crab",
    "ancient_elements:glitterpinch",
    "block_factorys_bosses:poison_area",
    "thalassophobia:reaverfish",
    "hordes:drowned_player",
    "rlovelyr:kitsune",
    "zombiesmore:tank_zombie",
    "thalassophobia:hesperornis",
    "thalassophobia:megastar",
    "thalassophobia:sunfish",
    "thalassophobia:giant_clam_natural_spawn",
    "thalassophobia:sonar_boom",
    "ancient_elements:wave",
    "alexsmobs:crow",
    "thalassophobia:crab_spawn",
    "alexsmobs:guster",
    "thalassophobia:eurypterid",
    "illager_world_war:villager_soldier_armed",
    "block_factorys_bosses:underworld_knight",
    "graveyard:wraith",
    "minecraft:pufferfish",
    "ancient_elements:sonar",
    "ancient_elements:scamp",
    "horrrs_pvz:fume_shroom",
    "minecraft:fox",
    "block_factorys_bosses:big_cage",
    "illager_world_war:villager_car",
    "alexsmobs:warped_toad",
    "thalassophobia:sea_bird",
    "thalassophobia:dead_archelon",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "thalassophobia:basilosaurus_jumping",
    "graveyard:acolyte",
    "illager_world_war:villager_soldier",
    "alexsmobs:emu",
    "alexsmobs:cockroach",
    "horrrs_pvz:bonk_choy",
    "thalassophobia:bathotrap_spawn",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "thalassophobia:baby_colossoteus",
    "rlovelyr:neko",
    "alexsmobs:capuchin_monkey",
    "hordes:husk_player",
    "minecraft:polar_bear",
    "ancient_elements:slash_effect_2",
    "minecraft:zombified_piglin",
    "ancient_elements:inflamed_wither_skeleton",
    "horrrs_pvz:corn_pitcher",
    "minecraft:turtle",
    "minecraft:sheep",
    "ancient_elements:inferno_explosion",
    "thalassophobia:maka_maka_in_ground",
    "ancient_elements:ancient_elemental_intro",
    "horrrs_pvz:angel_starfruit",
    "horrrs_pvz:puff_shroom",
    "quark:wraith",
    "graveyard:ghoul",
    "alexsmobs:rattlesnake",
    "quark:foxhound",
    "thalassophobia:sea_phantom",
    "ancient_elements:elementinium_blade_projektile",
    "thalassophobia:colossoteus_sonar_attack",
    "alexsmobs:bone_serpent_part",
    "horrrs_pvz:watermelon_pitcher",
    "alexsmobs:raccoon",
    "thalassophobia:mosasaurus_fossil_entity",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "alexsmobs:potoo",
    "horrrs_pvz:ice_gatling_pea_shooter",
    "ancient_elements:slash_effect",
    "alexsmobs:fly",
    "thalassophobia:giant_clam",
    "illager_world_war:pillager_car",
    "quark:shiba",
    "ancient_elements:puncheffect",
    "horrrs_pvz:high_nut_wall",
    "thalassophobia:orthoceras",
    "alexsmobs:straddler",
    "horrrs_pvz:three_peater",
    "illager_world_war:war_camp_check",
    "ancient_elements:flutterprism",
    "alexsmobs:sea_bear",
    "horrrs_pvz:iceberg_lettuce",
    "cannibal:cannibal_butcher",
    "alexsmobs:mudskipper",
    "ancient_elements:asteroid",
    "thalassophobia:plesiosaur_fossil_entity",
    "horrrs_pvz:heavenly_peach",
    "alexsmobs:sugar_glider",
    "ancient_elements:undead_gladiator",
    "alexsmobs:crimson_mosquito",
    "rlovelyr:dragon",
    "thalassophobia:ammonita",
    "block_factorys_bosses:ice_spike",
    "thalassophobia:orthoceras_cone_entity",
    "alexsmobs:orca",
    "thalassophobia:maka_maka",
    "valarian_conquest:battering_ram",
    "horrrs_pvz:pea_nut",
    "thalassophobia:ichthyosaurus_tamed",
    "alexsmobs:jerboa",
    "horrrs_pvz:melancholic_mushroom",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "thalassophobia:oarfish",
    "illager_world_war:villager_soldier_with_cannon_still",
    "horrrs_pvz:cold_snapdragon",
    "thalassophobia:archelon",
    "ancient_elements:whirl",
    "alexsmobs:comb_jelly",
    "thalassophobia:bathotrap",
    "thalassophobia:tuna",
    "ancient_elements:pouch_loot",
    "ancient_elements:galactrium_shockwave",
    "thalassophobia:dunkleosteus",
    "thalassophobia:megastar_natural_spawn",
    "thalassophobia:hesperornis_spawn",
    "ancient_elements:ancient_shockwave",
    "horrrs_pvz:spikeweed",
    "alexsmobs:skunk",
    "alexsmobs:enderiophage",
    "block_factorys_bosses:flaming_skeleton_guard_fireball",
    "ancient_elements:craterborn",
    "alexsmobs:sunbird",
    "ancient_elements:toxic_puddle",
    "alexsmobs:tasmanian_devil",
    "thalassophobia:basilosaurus_jumping_spawn",
    "illager_world_war:v_illager_soldier_armed_variant_1",
    "minecraft:cat",
    "alexsmobs:stradpole",
    "ancient_elements:cube",
    "horrrs_pvz:witch_hazel",
    "minecraft:tropical_fish",
    "horrrs_pvz:primal_peashooter",
    "illager_world_war:pillager_soldier_armed",
    "thalassophobia:megastar_spawn",
    "minecraft:panda",
    "minecraft:zombie_villager",
    "block_factorys_bosses:sandworm",
    "horrrs_pvz:umbrella_leaf",
    "alexsmobs:froststalker",
    "thalassophobia:whale",
    "minecraft:giant",
    "valarian_conquest:archer",
    "alexsmobs:lobster",
    "horrrs_pvz:starfruit",
    "thalassophobia:helicoprion",
    "alexsmobs:seagull",
    "horrrs_pvz:sun_bean",
    "alexsmobs:moose",
    "thalassophobia:yeti_crab_spawn",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "horrrs_pvz:ice_pea_shooter",
    "thalassophobia:sea_pickle_natural_spawn",
    "alexsmobs:warped_mosco",
    "ancient_elements:gemhost",
    "hordes:zombie_player",
    "ancient_elements:aurora_crystal_node",
    "horrrs_pvz:ice_watermelon_pitcher",
    "minecraft:husk",
    "thalassophobia:bull_shark",
    "rlovelyr:bunny",
    "mca:female_zombie_villager",
    "block_factorys_bosses:soul_skeleton",
    "ancient_elements:ancient_elemental",
    "horrrs_pvz:spikerock",
    "thalassophobia:goldfish",
    "illager_world_war:villager_soldier_with_knife",
    "horrrs_pvz:jalapeno",
    "alexsmobs:komodo_dragon",
    "block_factorys_bosses:yeti",
    "minecraft:donkey",
    "ancient_elements:celestium_shockwave",
    "thalassophobia:dead_archelon_spawn",
    "thalassophobia:maka_maka_spawn",
    "mutantmonsters:mutant_skeleton",
    "block_factorys_bosses:soul_area",
    "quark:stoneling",
    "minecraft:piglin_brute",
    "illager_world_war:cannon_with_soldier_pillager",
    "alexsmobs:crocodile",
    "quark:toretoise",
    "thalassophobia:maka_maka_swim",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "illager_world_war:pillager_solider_for_spawn",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "horrrs_pvz:explo_deo_nut",
    "valarian_conquest:catapult",
    "alexsmobs:blobfish",
    "graveyard:nameless_hanged",
    "horrrs_pvz:gatling_pea_shooter",
    "thalassophobia:anomalocaris",
    "alexsmobs:mimicube",
    "thalassophobia:panderodus",
    "alexsmobs:void_worm",
    "thalassophobia:plesiosaur",
    "thalassophobia:sea_pickle_spawn",
    "zombiesmore:boomer_charged",
    "ancient_elements:cosmic_collider_bomb_primed",
    "horrrs_pvz:cactus",
    "minecraft:parrot",
    "thalassophobia:sea_urchin_spawn",
    "ancient_elements:boulder",
    "alexsmobs:centipede_head",
    "horrrs_pvz:seed_a_agun",
    "thalassophobia:alpha_reaverfish",
    "block_factorys_bosses:pile_of_bones",
    "ancient_elements:piggy_bank",
    "minecraft:frog",
    "alexsmobs:banana_slug",
    "mutantmonsters:mutant_creeper",
    "illager_world_war:assault_pillager_soldier",
    "alexsmobs:mimic_octopus",
    "alexsmobs:bunfungus",
    "alexsmobs:void_worm_part",
    "thalassophobia:colossoteus_jumping",
    "minecraft:mule",
    "thalassophobia:electrophorus",
    "thalassophobia:colossoteus_fossil_entity",
    "horrrs_pvz:peashooter",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "minecraft:evoker",
    "thalassophobia:leedsichthys",
    "block_factorys_bosses:flaming_skeleton_guard_sword",
    "quark:forgotten",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "graveyard:ghouling",
    "thalassophobia:cnidaria",
    "valarian_conquest:ballista",
    "block_factorys_bosses:soul_knight_wither_skeleton",
    "ancient_elements:elemental_summon",
    "thalassophobia:manta",
    "graveyard:revenant",
    "horrrs_pvz:cabbage_pult",
    "horrrs_pvz:pepper_pult",
    "graveyard:lich",
    "horrrs_pvz:double_pea_shooter",
    "ancient_elements:aetherial_glaze",
    "thalassophobia:sea_urchin",
    "block_factorys_bosses:cage",
    "tombstone:grave_guardian",
    "thalassophobia:sea_pickle",
    "graveyard:corrupted_pillager",
    "illager_world_war:pillager_soldier_armed_variant_2",
    "illager_world_war:pillager_soldier_armed_variant_3",
    "horrrs_pvz:hypno_shroom",
    "illager_world_war:pillager_soldier_armed_variant_1",
    "thalassophobia:giant_clam_spawn",
    "alexsmobs:terrapin",
    "zombiesmore:cursed_zombie",
    "horrrs_pvz:potato_mines",
    "horrrs_pvz:torchwood",
    "alexsmobs:anaconda",
    "thalassophobia:basilosaurus",
    "thalassophobia:octus",
    "mca:grim_reaper",
    "thalassophobia:leech",
    "horrrs_pvz:chard_guard",
    "minecraft:pig",
    "horrrs_pvz:pumpkin",
    "alexsmobs:alligator_snapping_turtle",
    "minecraft:goat",
    "mca:male_zombie_villager",
    "mutantmonsters:mutant_enderman",
    "valarian_conquest:cannon",
    "minecraft:cod",
    "illager_world_war:villager_soldier_bringing_box",
    "alexsmobs:mantis_shrimp",
    "horrrs_pvz:chomper",
    "valarian_conquest:female_citizen",
    "alexsmobs:platypus",
    "thalassophobia:vertebrat",
    "mutantmonsters:spider_pig",
    "illager_world_war:pillager_soldier_still",
    "minecraft:cow",
    "thalassophobia:ichthyosaurus",
    "alexsmobs:rocky_roller",
    "illager_world_war:pillager_soldier",
    "block_factorys_bosses:fire_area",
    "alexsmobs:soul_vulture",
    "illager_world_war:assault_villager_soldier",
    "thalassophobia:xiphactinus",
    "illager_world_war:villager_soldier_still",
    "alexsmobs:blue_jay",
    "ancient_elements:flame_wall",
    "alexsmobs:toucan",
    "minecraft:salmon",
    "illager_world_war:pillager_conducer",
    "ancient_elements:aurora_crystal_slime",
    "thalassophobia:anglerfish",
    "alexsmobs:anteater",
    "thalassophobia:megapiranha",
    "alexsmobs:rain_frog",
    "thalassophobia:catfish",
    "minecraft:rabbit",
    "minecraft:pillager",
    "alexsmobs:murmur",
    "horrrs_pvz:coconut_cannons",
    "horrrs_pvz:twinsunflower",
    "minecraft:zoglin",
    "horrrs_pvz:sun_flower",
    "rlovelyr:honey",
    "thalassophobia:fish_meat",
    "alexsmobs:leafcutter_ant",
    "illager_world_war:plane_avec_pillager_soldier",
    "ancient_elements:cosmic_explosion",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "illager_world_war:plane_avec_villager_soldier",
    "alexsmobs:catfish",
    "ancient_elements:maul_shockwave",
    "mutantmonsters:endersoul_clone",
    "thalassophobia:mosasaur",
    "minecraft:piglin",
    "thalassophobia:hammerhead_shark",
    "horrrs_pvz:doom_shroom",
    "alexsmobs:skelewag",
    "thalassophobia:zapfin",
    "thalassophobia:crab_natural_spawn",
    "graveyard:corrupted_vindicator",
    "illager_world_war:villager_soldier_with_flame_thrower",
    "thalassophobia:alpha_reaverfish_skull",
    "ancient_elements:dig",
    "alexsmobs:elephant",
    "thalassophobia:puffer",
    "block_factorys_bosses:infernal_dragon",
    "cannibal:cannibal",
    "alexsmobs:gazelle",
    "thalassophobia:sea_urchin_natural_spawn",
    "valarian_conquest:soldier",
    "minecraft:sniffer",
    "thalassophobia:sea_bird_spawn",
    "thalassophobia:gulper_eel",
    "minecraft:zombie_horse",
    "horrrs_pvz:cherry_bomb",
    "minecraft:camel",
    "illager_world_war:villager_soldier_scarf",
    "thalassophobia:alligator_gar",
    "zombiesmore:crawler",
    "ancient_elements:undead_miner",
    "thalassophobia:sea_horse",
    "illager_world_war:villager_soldier_armed_variant_3",
    "illager_world_war:villager_soldier_armed_variant_2",
    "thalassophobia:colossoteus",
    "ancient_elements:wind_stream",
    "minecraft:ocelot",
    "minecraft:wolf",
    "horrrs_pvz:cattail",
    "block_factorys_bosses:dragon_guard_sword",
    "thalassophobia:tusoteuthis",
    "ancient_elements:topaz_crystal_slime",
    "thalassophobia:shark",
    "valarian_conquest:carriage"
]
