
#TFC: Real World Configuration
[map_settings]
	#
	#Map profile ID. Profiles are loaded from config/tfc_real_world/profiles/
	map_profile = "DEFAULT:FULL_EQUAL_EARTH"

[spawn_settings]
	#
	#Spawn location mode: GEOGRAPHIC (use longitude/latitude), RANDOM (from seed), or CLASSIC (use coordinates)
	#Allowed Values: GEOGRAPHIC, RANDOM, CLASSIC
	spawn_mode = "GEOGRAPHIC"
	#
	#Geographic longitude for the center position around which the spawn position is chosen (used in GEOGRAPHIC mode)
	#Range: -360.0 ~ 360.0
	spawn_center_longitude = 12.4964
	#
	#Geographic latitude for the center position around which the spawn position is chosen (used in GEOGRAPHIC mode)
	#Range: -90.0 ~ 90.0
	spawn_center_latitude = 41.9028

[tfc_spawn_settings]
	#
	#TFC option. The center X position around which the spawn position is chosen (used in CLASSIC mode)
	#Range: -100000 ~ 100000
	spawn_center_x = 486
	#
	#TFC option. The center Z position around which the spawn position is chosen (used in CLASSIC mode)
	#Range: -100000 ~ 100000
	spawn_center_z = -12262
	#
	#TFC option. The maximum distance from the spawn center the spawn position will be chosen
	#Range: 256 ~ 100000
	spawn_distance = 256

[world_generation]
	#
	#TFC option. If the bottom of the world is a single layer of flat bedrock, or random like vanilla
	flat_bedrock = false
	#
	#TFC option. Determines the nature of continents. Smaller values create smaller continents and more islands, larger values create larger, blobbier continents
	#Range: 0.0 ~ 1.0
	continentalness = 0.5
	#
	#TFC option. Affects how much grass generates in the world. Higher values indicate more grass coverage
	#Range: 0.0 ~ 1.0
	grass_density = 0.5
	#
	#TFC option. A number representing the temperature for an entire world, where -1.0 is polar and 1.0 is tropical
	#Range: -1.0 ~ 1.0
	temperature_constant = 0.0
	#
	#TFC option. A number representing the rainfall for an entire world, where -1.0 is arid and 1.0 is tropical
	#Range: -1.0 ~ 1.0
	rainfall_constant = 0.0
	#
	#TFC option. The distance between two temperature extremes, in blocks
	#Range: 256 ~ 100000
	temperature_scale = 20000
	#
	#TFC option. The distance between two rainfall extremes, in blocks
	#Range: 256 ~ 100000
	rainfall_scale = 20000

[generation_modes]
	#
	#Horizontal map radius in blocks
	#Range: 256 ~ 100000
	horizontal_scale = 40000
	#
	#Vertical map radius in blocks
	#Range: 256 ~ 100000
	vertical_scale = 20000
	#
	#Generate continents from map or procedurally
	continent_from_map = true
	#
	#Generate base land height and ocean depth from altitude map or procedurally
	altitude_from_map = true
	#
	#Generate hotspots from map or procedurally
	hotspots_from_map = true
	#
	#Generate climate parameters (temperature, rainfall, rainfall variance) from Köppen climate map or procedurally
	koppen_from_map = true

